CREATE ROLE registered 
WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN UNENCRYPTED PASSWORD 'password';
COMMENT ON ROLE registered IS 'user 0';

CREATE ROLE analyst 
WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN UNENCRYPTED PASSWORD 'password';
COMMENT ON ROLE analyst IS 'user 1';

CREATE ROLE admin 
WITH SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN UNENCRYPTED PASSWORD 'password';
COMMENT ON ROLE admin IS 'user 2';
